### ISSUE TITLE
Unable to build/install persistent 4.5.0 on Debian 9

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/persistent#114]
I discovered this issue when upgrading from Plone 5.2RC3 (using persistent 4.4.3) to Plone 5.2RC4-pending using persistent 4.5.0.

https://github.com/plone/Products.CMFPlone/issues/2900

I can reproduce this error using a Python 3.7.3 installation on a pretty fresh and update Debian 9 system. Python 3.7.3 is self-compiled without any special configuration of compile flags.

In the end there is something with the `cffi` module here?!

```
bin/pip install persistent==4.5.0
Collecting persistent==4.5.0
  Using cached https://files.pythonhosted.org/packages/15/30/cd03f249bf63dbed76f34822f7acb0b5c4a58cb776ce3818184a825695cc/persistent-4.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xzgp9es_/persistent/setup.py", line 137, in <module>
        entry_points={})
      File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python-3.7.3/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__
        k: v for k, v in attrs.items()
      File "/opt/python-3.7.3/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/ajung/sandboxes/ugent-portaal-plone-4x/lib/python3.7/site-packages/setuptools/dist.py", line 732, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-xzgp9es_/persistent/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-install-xzgp9es_/persistent/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-install-xzgp9es_/persistent/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "persistent/_ring_build.py", line 22, in <module>
        ffi = FFI()
      File "/tmp/pip-install-xzgp9es_/persistent/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: /tmp/pip-install-xzgp9es_/persistent/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/_cffi_backend.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xzgp9es_/persistent/
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


```

**Comment by jamadden** [comment]
I've seen something [very vaguely like that before](https://github.com/gevent/gevent/issues/612). Does your system mount `/tmp` without executable permissions (`noexec`)? If so, if you use a different temporary directory or mount with executable permissions, does it fix the error? Alternately, you may be able to ensure CFFI is installed before building the wheel (so it isn't put in the temporary directory).

**Comment by zopyx** [comment]
Good observation. 

/tmp is mounted without noexec

Setting TMPDIR or installing cffi manually before persistent works also.

Is this a regression or a feature of 4.5.0? As said: 4.4.3 as working in the same environment.

**Comment by mgedmin** [comment]
AFAICT 4.4.3 did not require `cffi`.

**Comment by jamadden** [comment]
> AFAICT 4.4.3 did not require cffi.

True. It had been an optional dependency for some time, but the (slow) fallback code was removed in #107. 

Very often the binary wheels would mitigate this, but there’s #113 (which I haven’t gotten around to addressing yet. )

One could also argue that there’s an underlying pip bug...

**Comment by icemac** [comment]
`persistent` 4.6.0+ has linux wheels (aka #113 is solved now). Can this issue be closed, too?

**Comment by zopyx** [comment]
The problem persists with 4.6.1. I still need to set `TMPDIR` to a local filesystem.

**Comment by mgedmin** [comment]
AFAIU this is a problem with CFFI in general, and not specific to persistent?

Has anybody reported it to CFFI's own bug tracker?
